version: "3.9"
services:
#  postgres:
#    container_name: MusicTradeDB
#    image: postgres:16-alpine3.20
#    restart: always
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_USER: ${DB_USER}
#      POSTGRES_PASSWORD: ${DB_PASS}
#      POSTGRES_DB: ${DB_NAME}
#    env_file: docker-compose.env
#
  minio:
    container_name: minio_storage
    image: minio/minio
    restart: always
    tty: true
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
        - /minio_storage:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin

    command: server --console-address ":9001" /data

    #  keycloak:
    #    image: bitnami/keycloak:latest
    #    container_name: keycloakAuthentication
    #    restart: always
    #    environment:
    #      DB_VENDOR: POSTGRES
    #      DB_DATABASE: ${DB_NAME}
    #      DB_SCHEMA: public
    #      DB_USER: ${DB_USER}
    #      DB_PASSWORD: ${DB_PASS}
    #      KEYCLOAK_USER: ${KC_USER}
    #      KEYCLOAK_PASSWORD: ${KC_PWD}
    #    depends_on:
    #      - postgres
    #    env_file: docker-compose.env
