version: "3.9"
services:
  postgres:
    container_name: MusicTradeDB
    image: postgres:16-alpine3.20
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    env_file: docker-compose.env

  minio:
    container_name: minio_storage
    image: minio/minio
    restart: always
    tty: true
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
        - /minio_storage:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin

    command: server --console-address ":9001" /data

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.2
    container_name: keycloak
    command:
      - start --auto-build --db postgres --hostname-strict-https false --hostname-strict false --proxy edge --http-enabled true --import-realm --spi-user-profile-legacy-user-profile-read-only-attributes *_RES_ACCESS_MODE
    environment:
      KC_DB_URL: jdbc:postgresql://keycloak-postgres:5432/postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KC_DB_SCHEMA: public
      KC_FEATURES: preview
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8282:8080"
    depends_on:
      - postgres

    #  keycloak:
    #    image: bitnami/keycloak:latest
    #    container_name: keycloakAuthentication
    #    restart: always
    #    environment:
    #      DB_VENDOR: POSTGRES
    #      DB_DATABASE: ${DB_NAME}
    #      DB_SCHEMA: public
    #      DB_USER: ${DB_USER}
    #      DB_PASSWORD: ${DB_PASS}
    #      KEYCLOAK_USER: ${KC_USER}
    #      KEYCLOAK_PASSWORD: ${KC_PWD}
    #    depends_on:
    #      - postgres
    #    env_file: docker-compose.env
