version: "3.9"
services:
  postgres:
    container_name: MusicTradeDB
    image: postgres:16-alpine3.20
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file: docker-compose.env

  postgres_kc:
    container_name: PostgresKC
    image: postgres:latest
    restart: always
    ports:
      - "5436:5436"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ${KC_DB_NAME}
    env_file: docker-compose.env

  minio:
    container_name: minio_storage
    image: minio/minio
    restart: always
    tty: true
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
        - /minio_storage:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server --console-address ":9001" /data

  keycloak:
    image: bitnami/keycloak
    container_name: keycloak
    environment:
      KC_DB_URL: ${KC_DB_URL}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_DB_SCHEMA: public
      KC_FEATURES: preview
      KEYCLOAK_ADMIN: ${KC_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KC_PASSWORD}
    ports:
      - "8081:8081"
    depends_on:
      - postgres_kc
    env_file: docker-compose.env
